x-image: &image
  image: murilochianfa/cpp-fraud-detection-rinha-2026:latest

services:
  api1:
    <<: *image
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/api", "8001"]
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "155M"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8001/ready || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 30

  api2:
    <<: *image
    command: ["/api", "8002"]
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "155M"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8002/ready || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 30

  lb:
    <<: *image
    command: ["/lb", "9999", "api1:8001", "api2:8002"]
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "40M"

networks:
  rinha:
    driver: bridge
